<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://localhost:8080/" />
<title>login[CreateNew-Login-Logout-Login]</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">login[CreateNew-Login-Logout-Login]</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>http://localhost:8080/</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>//button</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=email</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=password</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=a.pull-right</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//button</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>css=a.pull-right</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=first_name</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=last_name</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>name=email</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=div.col-sm-7 &gt; #password</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=password_confirm</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=phone_number</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>name=acc_customer</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>name=acc_business</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=first_name</td>
	<td>Tester</td>
</tr>
<tr>
	<td>type</td>
	<td>id=last_name</td>
	<td>Testovsky</td>
</tr>
<tr>
	<td>type</td>
	<td>name=email</td>
	<td>test@markschk.ru</td>
</tr>
<tr>
	<td>type</td>
	<td>css=div.col-sm-7 &gt; #password</td>
	<td>tested123</td>
</tr>
<tr>
	<td>type</td>
	<td>id=password_confirm</td>
	<td>tested123</td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>id=phone_number</td>
	<td>8001234567</td>
</tr>

</tbody></table>
</body>
</html>
