<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://localhost:8080/" />
<title>login[CreateNew-Login-Logout-Login]</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">login[CreateNew-Login-Logout-Login]</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>http://127.0.0.1:8080/</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>//button</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=email</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=password</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=a.pull-right</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//button</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>css=a.pull-right</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=first_name</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=last_name</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>name=email</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=div.col-sm-7 &gt; #password</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=password_confirm</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=phone_number</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>name=acc_customer</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>name=acc_business</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=first_name</td>
	<td>Tester</td>
</tr>
<tr>
	<td>type</td>
	<td>id=last_name</td>
	<td>Testovsky</td>
</tr>
<tr>
	<td>type</td>
	<td>name=email</td>
	<td>test@markschk.ru</td>
</tr>
<tr>
	<td>type</td>
	<td>css=div.col-sm-7 &gt; #password</td>
	<td>tested123</td>
</tr>
<tr>
	<td>type</td>
	<td>id=password_confirm</td>
	<td>tested123</td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>id=phone_number</td>
	<td>8001234567</td>
</tr>
<!--Аккаунт уже создан, потому проверяем на ошибку-->
<tr>
	<td>clickAndWait</td>
	<td>name=acc_customer</td>
	<td></td>
</tr>
<tr>
	<td>verifyText</td>
	<td>css=div.alert.alert-danger</td>
	<td>× This email is already in use.</td>
</tr>
<tr>
	<td>type</td>
	<td>css=div.col-sm-7 &gt; #password</td>
	<td>tested123</td>
</tr>
<tr>
	<td>type</td>
	<td>id=password_confirm</td>
	<td>tested123</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>name=acc_business</td>
	<td></td>
</tr>
<tr>
	<td>verifyText</td>
	<td>css=div.alert.alert-danger</td>
	<td>× This email is already in use.</td>
</tr>
<!--Теперь делаем логин с известными данными-->
<tr>
	<td>click</td>
	<td>//button</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=email</td>
	<td>test@markschk.ru</td>
</tr>
<tr>
	<td>type</td>
	<td>id=password</td>
	<td>tested123</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>css=button.btn.btn-primary</td>
	<td></td>
</tr>
<tr>
	<td>assertTitle</td>
	<td>AppointmentPro.com: Book an Appointment with a Business in Your Area!</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=img[alt=&quot;AppointmentPro&quot;]</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>link=For Businesses</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>link=Help</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>link=About AppointmentPro</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>link=FAQ &amp; Help</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>link=Contact Us</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=search</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=place</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=date</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=submit_search</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>id=map-canvas</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>class=business_lists</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=About AppointmentPro</td>
	<td></td>
</tr>
<tr>
	<td>open</td>
	<td>http://127.0.0.1:8080/</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=FAQ &amp; Help</td>
	<td></td>
</tr>
<tr>
	<td>open</td>
	<td>http://127.0.0.1:8080/</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Profile</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=div.introjs-overlay</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=modal_popup</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=h1</td>
	<td></td>
</tr>
<tr>
	<td>assertText</td>
	<td>css=h1</td>
	<td>Tester Testovsky's Profile Settings</td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>link=General</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>link=Settings</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=h3.panel-title</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=div.col-sm-6.row-offset-20 &gt; div.panel.panel-primary &gt; div.panel-heading &gt; h3.panel-title</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>//div[2]/div/div/h3</td>
	<td></td>
</tr>
<tr>
	<td>assertElementPresent</td>
	<td>css=div.col-sm-12 &gt; div.panel.panel-primary &gt; div.panel-heading &gt; h3.panel-title</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>
